# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Verify Helm Chart
  displayName: 'Verify Helm Chart'
  jobs:
  - job: VerifyHelmChart
    displayName: 'Verify Helm Chart'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - script: |
        helm lint ./helm-chart
      displayName: 'Lint Helm Chart'
