# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ACR_SC: ARM-SC-ADO
  ACR_RG: the_dc_space
  ACR_NAME: dogsbody

stages:
- stage: Verify_Helm_Chart
  displayName: 'Verify Helm Chart'
  jobs:
  - job: VerifyHelmChart
    displayName: 'Verify Helm Chart'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - script: |
        helm lint .
      displayName: 'Lint Helm Chart'

- stage : Package_Helm_Chart
  displayName: 'Package Helm Chart'
  dependsOn: Verify_Helm_Chart
  jobs:
  - job: PackageHelmChart
    displayName: 'Package Helm Chart'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'

    - task: HelmDeploy@1
      displayName: Login to ACR for Helm
      inputs:
        connectionType: 'None'
        command: 'login'
        azureSubscriptionForACR: '$(ACR_SC)'
        azureResourceGroupForACR: '$(ACR_RG)'
        azureContainerRegistry: '$(ACR_NAME)'

    - task: HelmDeploy@1
      displayName: 'Package Helm Chart'
      inputs:
        connectionType: 'None'
        command: 'package'
        chartPathForACR: '.'
        chartNameForACR: 'vsftpd'
        destination: '$(Build.ArtifactStagingDirectory)'
        azureSubscriptionForACR: '$(ACR_SC)'
        azureResourceGroupForACR: '$(ACR_RG)'
        azureContainerRegistry: '$(ACR_NAME)'

