# Default values for vsftpd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# THis will set the namespace fo the service
namespace: vsftpd

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: dogsbody.azurecr.io/vsftpd:v1.0.0
  # This sets the pull policy for images.
  pullPolicy: always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This section sets all the ports fo the FTP service
ftp: 
  pasvAddress: ""   #Passive IP address (set to your external HAProxy)
  controlPort: 21   #FTP control port
  pasvMinPort: 10000  #Minimum passive port
  pasvMaxPort: 10250  #Maximum passive port

# This section sets all the ports for the SFTP service
sftp:
  port: 22  #SFTP port

service:
  type: ClusterIP
  passive:
    type: NodePort
    nodePortPassiveMin: 32100  # This is the base node port for passive services, it will be incremented for each passive port.

# Sets the user config path inside the container
userConfigPath: "/etc/vsftpd/users.json"

environment: dev

# This is the reference to the users.json file that is used to set the users for the vsftpd server.
users: |
  {}

storageClassName: ""

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  runAsNonRoot: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ""
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  runAsUser: ""