# Default values for vsftpd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# THis will set the namespace fo the service
namespace: vsftpd

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# Set minimum available pods for PodDisruptionBudget
minAvailable: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: dogsbody.azurecr.io/vsftpd:v1.1.0
  # This sets the pull policy for images.
  pullPolicy: always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  sftp:
    type: LoadBalancer  # SFTP service type, default is ClusterIP
    port: 22  #SFTP port
    publicIPv4: ""  # Public IP for the SFTP service, if needed
  ftp:
    type: LoadBalancer
    publicIPv4: ""  # Public IPv4 for the FTP service, if needed
    pasvAddress: ""   #Passive IP address (set to your external HAProxy)
    controlPort: 21   #FTP control port
    pasvMinPort: 10000  #Minimum passive port
    pasvMaxPort: 10025  #Maximum passive port
  loadBalancerSourceRanges: # Sets allowed Source IP's for the LoadBalancer
    - ""

resources:
  limits:
    memory: "512Mi"
  requests:
    memory: "128Mi"
  

# Sets the user config path inside the container
userConfigPath: "/etc/vsftpd/users.json"

environment: dev

# This is the reference to the users.json file that is used to set the users for the vsftpd server.
users: |
  {}

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: ""
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault