---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: ftp-server
  ports:
    - name: ftp
      port: {{ .Values.containerPorts.ftp }}
      targetPort: {{ .Values.containerPorts.ftp }}
    - name: sftp
      port: {{ .Values.containerPorts.sftp }}
      targetPort: {{ .Values.containerPorts.sftp }}
    - name: pasvmin
      port: {{ .Values.containerPorts.pasvmin }}
      targetPort: {{ .Values.containerPorts.pasvmin }}
    - name: pasvmax 
      port: {{ .Values.containerPorts.pasvmax }}
      targetPort: {{ .Values.containerPorts.pasvmax }}