---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sftp-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.sftp.type | default "ClusterIP" }}
  selector:
    app: ftp-server
  ports:
    - name: sftp
      port: {{ .Values.service.sftp.port }}
      targetPort: {{ .Values.service.sftp.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ftp-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.ftp.type | default "NodePort" }}
  selector:
    app: ftp-server
  ports:
    - name: ftp
      port: {{ .Values.service.ftp.controlPort }}
      targetPort: {{ .Values.service.ftp.controlPort }}
    {{- $baseNodePort := int .Values.service.ftp.nodePortPassiveMin }}
    {{- $pasvMinPort := int .Values.service.ftp.pasvMinPort }}
    {{- $pasvMaxPort := int .Values.service.ftp.pasvMaxPort }}
    {{- range $i, $port := untilStep $pasvMinPort (int (add1 $pasvMaxPort)) 1 }}
    - name: pasv-{{ $port }}
      port: {{ $port }}
      targetPort: {{ $port }}
      nodePort: {{ add $baseNodePort $i }}
    {{- end }}