#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: {{ .Release.Name }}-pv
#  namespace: {{ .Values.namespace }}
#spec:
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 10Gi
#  hostPath:
#    path: /data # adjust path on host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName | default "" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi